# Site settings
title: Maera
description: > # this means to ignore newlines until "baseurl:"
  Maera is a tool for working with RIPE Atlas.
baseurl: "/maera" # the subpath of your site, e.g. /blog/
twitter_username: mikkelmonrad
github_username:  monrad

#GA
google_analytics: UA-60830157-1

# Build settings
markdown: kramdown
